/* AMACX EU - client data (window.DASHBOARD_DATA).
   GENERATED by tools/build-amacx-data.ps1 - do not hand-edit; re-run the generator.
   ACTUALS: MerchantSpring (clean monthly series). BUDGETS: Google Sheet. NLD excluded (pending launch).
   dataSource.type must be 'static' so the live proxy overlay does not replace these. */
window.DASHBOARD_DATA = {
  dateRanges: {
  'may': {
    label: 'May 2026', shortLabel: 'May 2026',
    rev: '€8,178', revD: '▲ 25.7% MoM', revC: 'du', revS: 'vs €6,505 Apr',
    adSales: '€4,747', adSalesD: '▲ 60.3% MoM', adSalesC: 'du', adSalesS: '58.0% of revenue',
    tacos: '28.2%', tacosD: '▼ 2.7pp vs Apr', tacosC: 'du', tacosS: 'Target <20%',
    roas: '3.55×', roasD: '▲ 0.31× vs Apr', roasC: 'du', roasS: '269 units · AOV €33.25',
    spend: '€2,307', spendD: '▲ 14.9% MoM', spendC: 'df', spendS: 'vs €2,008 Apr',
    tacosAd: '28.2%', tacosAdD: '▼ 2.7pp vs Apr', tacosAdC: 'du', tacosAdS: 'Target <20%',
    roasAd: '3.55×', roasAdD: '▲ 0.31× vs Apr', roasAdC: 'du', roasAdS: '€8,178 revenue',
    aov: '€33.25', aovD: '', aovC: 'df', aovS: '246 orders May',
    mktRows: [
      ['DE','de','€1,200','€532','bg','▼ €668 under','€1,948','br','27.3%'],
      ['FR','fr','€500','€586','br','▲ €86 over','€2,091','br','28.0%'],
      ['ES','es','€350','€602','br','▲ €252 over','€1,948','br','30.9%'],
      ['IT','it','€450','€587','br','▲ €137 over','€2,191','ba','26.8%'],
      ['NLD','nl','€0','€0','bb','Early launch','€0','bb','—'],
      ['Total EU',null,'€2,500','€2,307','bg','92% utilised','€8,178','br','28.2%']
    ],
    campaignMix: { slices:[ {name:'Sponsored Products',color:'#404935',pct:82.5,sales:'€28.7k',acos:'45.1%'}, {name:'Sponsored Brands',color:'#9caf78',pct:9.3,sales:'€4.5k',acos:'32.6%'}, {name:'Sponsored Display',color:'#e8a87c',pct:8.3,sales:'€0.0k',acos:'n/a'} ] },
  },
  '3m': {
    label: 'Mar–May 2026', shortLabel: 'Mar–May 2026',
    rev: '€19,302', revD: '3-month actuals', revC: 'du', revS: '',
    adSales: '€9,998', adSalesD: '3-month actuals', adSalesC: 'df', adSalesS: '51.8% of revenue',
    tacos: '27.6%', tacosD: '', tacosC: 'df', tacosS: 'Target <20%',
    roas: '3.63×', roasD: '', roasC: 'df', roasS: '',
    spend: '€5,321', spendD: '3-month actuals', spendC: 'df', spendS: '',
    tacosAd: '27.6%', tacosAdD: '', tacosAdC: 'df', tacosAdS: 'Target <20%',
    roasAd: '3.63×', roasAdD: '', roasAdC: 'df', roasAdS: '€19,302 revenue',
    aov: '€32.88', aovD: '', aovC: 'df', aovS: '',
    mktRows: [
      ['DE','de','€2,450','€1,577','bg','▼ €873 under','€5,844','ba','27.0%'],
      ['FR','fr','€1,350','€1,236','bg','▼ €114 under','€4,416','br','28.0%'],
      ['ES','es','€950','€1,235','br','▲ €285 over','€4,364','br','28.3%'],
      ['IT','it','€1,200','€1,273','br','▲ €73 over','€4,678','br','27.2%'],
      ['NLD','nl','€0','€0','bb','Early launch','€0','bb','—'],
      ['Total EU',null,'€5,950','€5,321','bg','89% utilised','€19,302','br','27.6%']
    ],
    campaignMix: { slices:[ {name:'Sponsored Products',color:'#404935',pct:82.5,sales:'€28.7k',acos:'45.1%'}, {name:'Sponsored Brands',color:'#9caf78',pct:9.3,sales:'€4.5k',acos:'32.6%'}, {name:'Sponsored Display',color:'#e8a87c',pct:8.3,sales:'€0.0k',acos:'n/a'} ] },
  },
  '6m': {
    label: 'Jan–May 2026 (YTD)', shortLabel: 'Jan–May 2026',
    rev: '€26,321', revD: '5-month actuals', revC: 'du', revS: '',
    adSales: '€12,852', adSalesD: '5-month actuals', adSalesC: 'df', adSalesS: '48.8% of revenue',
    tacos: '22.1%', tacosD: '', tacosC: 'df', tacosS: 'Target <20%',
    roas: '4.52×', roasD: '', roasC: 'df', roasS: '',
    spend: '€5,822', spendD: '5-month actuals', spendC: 'df', spendS: '',
    tacosAd: '22.1%', tacosAdD: '', tacosAdC: 'df', tacosAdS: 'Target <20%',
    roasAd: '4.52×', roasAdD: '', roasAdC: 'df', roasAdS: '€26,321 revenue',
    aov: '€32.46', aovD: '', aovC: 'df', aovS: '',
    mktRows: [
      ['DE','de','€3,300','€1,802','bg','▼ €1,498 under','€8,950','ba','20.1%'],
      ['FR','fr','€1,850','€1,325','bg','▼ €525 under','€5,438','ba','24.4%'],
      ['ES','es','€1,300','€1,303','br','▲ €3 over','€5,247','ba','24.8%'],
      ['IT','it','€1,800','€1,391','bg','▼ €409 under','€6,686','ba','20.8%'],
      ['NLD','nl','€0','€0','bb','Early launch','€0','bb','—'],
      ['Total EU',null,'€8,250','€5,822','bg','71% utilised','€26,321','ba','22.1%']
    ],
    campaignMix: { slices:[ {name:'Sponsored Products',color:'#404935',pct:82.5,sales:'€28.7k',acos:'45.1%'}, {name:'Sponsored Brands',color:'#9caf78',pct:9.3,sales:'€4.5k',acos:'32.6%'}, {name:'Sponsored Display',color:'#e8a87c',pct:8.3,sales:'€0.0k',acos:'n/a'} ] },
  },
  '2025': {
    label: 'Full Year 2025', shortLabel: 'FY 2025',
    rev: '€41,404', revD: 'Full year actuals', revC: 'du', revS: '',
    adSales: '€21,292', adSalesD: 'Full year actuals', adSalesC: 'df', adSalesS: '51.4% of revenue',
    tacos: '27.4%', tacosD: '', tacosC: 'df', tacosS: 'Target <20%',
    roas: '3.65×', roasD: '', roasC: 'df', roasS: '',
    spend: '€11,337', spendD: 'Full year actuals', spendC: 'df', spendS: '',
    tacosAd: '27.4%', tacosAdD: '', tacosAdC: 'df', tacosAdS: 'Target <20%',
    roasAd: '3.65×', roasAdD: '', roasAdC: 'df', roasAdS: '€41,404 revenue',
    aov: '€30.42', aovD: '', aovC: 'df', aovS: '',
    mktRows: [
      ['DE','de','€12,680','€6,440','bg','▼ €6,240 under','€25,478','ba','25.3%'],
      ['FR','fr','€2,400','€1,672','bg','▼ €728 under','€4,529','br','36.9%'],
      ['ES','es','€1,300','€1,234','bg','▼ €66 under','€4,545','br','27.1%'],
      ['IT','it','€2,500','€1,991','bg','▼ €509 under','€6,852','br','29.1%'],
      ['NLD','nl','€0','€0','bb','Early launch','€0','bb','—'],
      ['Total EU',null,'€18,880','€11,337','bg','60% utilised','€41,404','br','27.4%']
    ],
    campaignMix: { slices:[ {name:'Sponsored Products',color:'#404935',pct:82.5,sales:'€28.7k',acos:'45.1%'}, {name:'Sponsored Brands',color:'#9caf78',pct:9.3,sales:'€4.5k',acos:'32.6%'}, {name:'Sponsored Display',color:'#e8a87c',pct:8.3,sales:'€0.0k',acos:'n/a'} ] },
  },
  '12m': {
    label: 'Last 12 Months', shortLabel: 'Last 12 Months',
    rev: '€60,253', revD: 'Trailing 12 months', revC: 'du', revS: '',
    adSales: '€31,539', adSalesD: 'Trailing 12 months', adSalesC: 'df', adSalesS: '52.3% of revenue',
    tacos: '26.0%', tacosD: '', tacosC: 'df', tacosS: 'Target <20%',
    roas: '3.84×', roasD: '', roasC: 'df', roasS: '',
    spend: '€15,693', spendD: 'Trailing 12 months', spendC: 'df', spendS: '',
    tacosAd: '26.0%', tacosAdD: '', tacosAdC: 'df', tacosAdS: 'Target <20%',
    roasAd: '3.84×', roasAdD: '', roasAdC: 'df', roasAdS: '€60,253 revenue',
    aov: '€31.38', aovD: '', aovC: 'df', aovS: '',
    mktRows: [
      ['DE','de','€14,500','€7,399','bg','▼ €7,101 under','€28,165','ba','26.3%'],
      ['FR','fr','€3,850','€2,709','bg','▼ €1,141 under','€9,569','br','28.3%'],
      ['ES','es','€2,600','€2,537','bg','▼ €63 under','€9,604','ba','26.4%'],
      ['IT','it','€4,150','€3,048','bg','▼ €1,102 under','€12,915','ba','23.6%'],
      ['NLD','nl','€0','€0','bb','Early launch','€0','bb','—'],
      ['Total EU',null,'€25,100','€15,693','bg','63% utilised','€60,253','ba','26.0%']
    ],
    campaignMix: { slices:[ {name:'Sponsored Products',color:'#404935',pct:82.5,sales:'€28.7k',acos:'45.1%'}, {name:'Sponsored Brands',color:'#9caf78',pct:9.3,sales:'€4.5k',acos:'32.6%'}, {name:'Sponsored Display',color:'#e8a87c',pct:8.3,sales:'€0.0k',acos:'n/a'} ] },
  }
  },
  sections: {
    overview: {
      buyBox: [
        {flag:'de',label:'Germany',pct:50,valText:'49.8%',color:'red'},
        {flag:'fr',label:'France',pct:99,valText:'98.9%',color:'green'},
        {flag:'es',label:'Spain',pct:93,valText:'93.1%',color:'green'},
        {flag:'it',label:'Italy',pct:94,valText:'94.3%',color:'green'}
      ],
      cvr: { val:'4.4%', note:'recent month · 5,543 sessions', sub:'All EU · session conversion' },
      stockWarn: { badge:'6 OOS SKUs', items:[
        {level:'red',title:'Fast Bar Lemon — OOS all markets',sub:'B086XB1N46 · since 14 May'},
        {level:'red',title:'Hydro Tabs Orange — DE/FR/ES',sub:'B0CCJW62HZ · since 3 Jun'},
        {level:'amber',title:'Energy Drink Lemon 1kg — FR/ES/IT',sub:'B0GS21WT66 · since 15 Apr'},
        {level:'amber',title:'Turbo Drink Watermelon — FR/ES/IT',sub:'B0GSWHPXQV · since 5 Jun'}
      ] }
    },
    pnl: {
      fixedLabel: 'Last 12 months (Jun 2025–May 2026) · financial basis',
      summary: [ {val:'€58,530',lbl:'Net Revenue',color:'brand'}, {val:'€37,697',lbl:'Total Costs',color:'red'}, {val:'€20,833',lbl:'Net Profit',color:'green'} ],
      margin: { pct:'35.6%', pctColor:'green', note:'Trailing 12 months · financial basis (MerchantSpring) · differs from Overview which is on a sales-attribution basis', rows:[
        {lbl:'Net Revenue', val:'€58,530'},
        {lbl:'Marketplace Fees', val:'-€9,838', color:'red'},
        {lbl:'Ad Spend', val:'-€16,035', color:'red'},
        {lbl:'COGS', val:'-€11,824', color:'red'},
        {lbl:'Net Profit', val:'€20,833', color:'green', strong:true}
      ] },
      mkt: [
        {name:'Germany',flag:'de',revenue:'€30,826',adspend:'€7,723',net:'€12,184',netColor:'green',margin:'39.5%',marginCls:'bg'},
        {name:'France',flag:'fr',revenue:'€8,145',adspend:'€2,760',net:'€2,251',netColor:'green',margin:'27.6%',marginCls:'ba'},
        {name:'Spain',flag:'es',revenue:'€7,941',adspend:'€2,332',net:'€2,536',netColor:'green',margin:'31.9%',marginCls:'bg'},
        {name:'Italy',flag:'it',revenue:'€11,618',adspend:'€3,220',net:'€3,862',netColor:'green',margin:'33.2%',marginCls:'bg'}
      ],
      statement: { groups:[
        { header:'Income', rows:[
          {lbl:'Product sales', amount:'€57,435', pct:'98.1%', unit:'€28.93'},
          {lbl:'Refunds', amount:'-€905', pct:'-1.5%', unit:'-€0.46'},
          {lbl:'Reimbursements', amount:'€2', pct:'0.0%', unit:'€0.00'},
          {lbl:'Promotions', amount:'-€2,600', pct:'-4.4%', unit:'-€1.31'},
          {lbl:'Other income', amount:'€4,598', pct:'7.9%', unit:'€2.32'},
          {lbl:'Net revenue', amount:'€58,530', pct:'100.0%', unit:'€29.49', total:true}
        ] },
        { header:'Expenses', rows:[
          {lbl:'Advertising', amount:'€16,035', pct:'27.4%', unit:'€8.08'},
          {lbl:'Selling fees', amount:'€9,803', pct:'16.7%', unit:'€4.94'},
          {lbl:'Cost of goods', amount:'€11,824', pct:'20.2%', unit:'€5.96'},
          {lbl:'Refunds and returns', amount:'€35', pct:'0.1%', unit:'€0.02'},
          {lbl:'Total expenses', amount:'€37,697', pct:'64.4%', unit:'€18.99', total:true}
        ] },
        { header:'Profit', rows:[
          {lbl:'PROFIT', amount:'€20,833', pct:'35.6%', unit:'€10.49', total:true, profit:true},
          {lbl:'Profit %', amount:'35.6%', accent:'green'}
        ] },
        { header:'Metrics', rows:[
          {lbl:'Estimated payout', amount:'€32,657', unit:'€16.45'},
          {lbl:'TACOS %', amount:'27.4%'}
        ] }
      ] }
    },
    advertising: {
      campaigns: [
        {name:'DE · Brand Protection',type:'Sponsored Brands',spend:'€916',sales:'€3,818',acos:'24.0%',acosCls:'bg',roas:'4.17×',cpc:'€0.96',status:'Active',statusCls:'bg'},
        {name:'IT · Brand Defence',type:'Sponsored Products',spend:'€902',sales:'€4,586',acos:'19.7%',acosCls:'bg',roas:'5.08×',cpc:'€0.86',status:'Active',statusCls:'bg'},
        {name:'DE · Turbo Gels',type:'Sponsored Products',spend:'€854',sales:'€640',acos:'133.5%',acosCls:'br',roas:'0.75×',cpc:'€1.60',status:'Paused',statusCls:'ba'},
        {name:'FR · Brand Defense',type:'Sponsored Products',spend:'€702',sales:'€2,836',acos:'24.8%',acosCls:'bg',roas:'4.04×',cpc:'€1.20',status:'Active',statusCls:'bg'},
        {name:'DE · PAT Brand Defence',type:'Sponsored Products',spend:'€695',sales:'€4,858',acos:'14.3%',acosCls:'bg',roas:'6.99×',cpc:'€0.77',status:'Active',statusCls:'bg'},
        {name:'ES · PAT Brand Defence',type:'Sponsored Products',spend:'€607',sales:'€2,746',acos:'22.1%',acosCls:'bg',roas:'4.52×',cpc:'€0.69',status:'Active',statusCls:'bg'},
        {name:'DE · Energy Gels (Auto)',type:'Sponsored Products',spend:'€558',sales:'€556',acos:'100.4%',acosCls:'br',roas:'1.00×',cpc:'€1.47',status:'Active',statusCls:'ba'},
        {name:'DE · Fast Oat & Recovery Bars',type:'Sponsored Products',spend:'€463',sales:'€1,109',acos:'41.7%',acosCls:'ba',roas:'2.40×',cpc:'€1.65',status:'Active',statusCls:'bg'}
      ]
    },
    inventory: {
      kpis: [
        {bar:'green',lbl:'In Stock',val:'124',dCls:'du',d:'listings',s:'across DE/FR/ES/IT'},
        {bar:'red',lbl:'Out of Stock',val:'16',dCls:'dd',d:'listings suppressed',s:'6 unique SKUs'},
        {bar:'#404935',lbl:'Active SKUs',val:'140',dCls:'df',d:'EU listings',s:'~35 per market'},
        {bar:'amber',lbl:'SKUs to Restock',val:'6',dCls:'df',dColor:'amber',d:'OOS in 1+ market',s:'see priority list'}
      ],
      stock: [
        {dot:'dr',name:'Fast Bar Lemon — DE/FR/ES/IT',note:'B086XB1N46 · OOS all markets (14 May)',units:'0 units',unitsColor:'red',days:'OOS',daysColor:'red'},
        {dot:'dr',name:'Hydro Tabs Orange — DE/FR/ES',note:'B0CCJW62HZ · OOS (3 Jun)',units:'0 units',unitsColor:'red',days:'OOS',daysColor:'red'},
        {dot:'dr',name:'Energy Drink Lemon 1kg — FR/ES/IT',note:'B0GS21WT66 · OOS (15 Apr)',units:'0 units',unitsColor:'red',days:'OOS',daysColor:'red'},
        {dot:'dr',name:'Turbo Drink Watermelon — FR/ES/IT',note:'B0GSWHPXQV · OOS (5 Jun)',units:'0 units',unitsColor:'red',days:'OOS',daysColor:'red'},
        {dot:'dr',name:'Energy Drink Forest Fruit 320g — DE/FR',note:'B0GZ469Z98 · OOS (10 Jun)',units:'0 units',unitsColor:'red',days:'OOS',daysColor:'red'},
        {dot:'dr',name:'Turbo Drink Lemon 850g — IT',note:'B0C9MXWW77 · OOS (17 Mar)',units:'0 units',unitsColor:'red',days:'OOS',daysColor:'red'},
        {dot:'dg',name:'Energy Drink Forest Fruit 1kg — DE',note:'B0GSWK3DNX · Healthy',units:'560 units',days:'>12 mo'},
        {dot:'dg',name:'Turbo Drink Lemon 850g — DE',note:'B0GSWW3HW2 · Healthy',units:'305 units',days:'>12 mo'},
        {dot:'dg',name:'Energy Gel Citrus — DE',note:'B0CRFD8L2X · Healthy',units:'297 units',days:'>12 mo'},
        {dot:'dg',name:'Energy Gel Cola/Caffeine — DE',note:'B0CRFB42XS · Healthy',units:'277 units',days:'>12 mo'}
      ],
      restock: [
        {level:'red',title:'Fast Bar Lemon — all 4 markets',sub:'B086XB1N46 · OOS since 14 May · top restock priority'},
        {level:'red',title:'Energy Drink Lemon 1kg — FR/ES/IT',sub:'B0GS21WT66 · OOS since 15 Apr'},
        {level:'red',title:'Turbo Drink Watermelon — FR/ES/IT',sub:'B0GSWHPXQV · OOS since 5 Jun'},
        {level:'amber',title:'Hydro Tabs Orange — DE/FR/ES',sub:'B0CCJW62HZ · OOS since 3 Jun'}
      ]
    },
    products: {
      kpis: [
        {bar:'#404935',lbl:'Active SKUs',val:'140',dCls:'df',d:'EU listings',s:'~35 per market'},
        {bar:'green',lbl:'Orders (12mo)',val:'1,361',dCls:'du',d:'trailing 12 months',s:'~113/mo'},
        {bar:'blue',lbl:'AOV',val:'€42',dCls:'df',d:'12-mo avg',s:'blended EU'},
        {bar:'amber',lbl:'ASP',val:'€28.90',dCls:'df',d:'12-mo avg',s:'per unit'}
      ],
      table: [
        {name:'Germany',flag:'de',revenue:'€27,939',units:'964',orders:'640',cvr:'4.4%',cvrCls:'ba',aov:'€43.65'},
        {name:'France',flag:'fr',revenue:'€8,801',units:'298',orders:'199',cvr:'7.8%',cvrCls:'bg',aov:'€44.23'},
        {name:'Spain',flag:'es',revenue:'€8,728',units:'317',orders:'214',cvr:'5.8%',cvrCls:'ba',aov:'€40.79'},
        {name:'Italy',flag:'it',revenue:'€11,967',units:'406',orders:'308',cvr:'3.6%',cvrCls:'ba',aov:'€38.85'}
      ]
    }
  }
};
